version: '3.8'

services:
  # Streamlit Web App Service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_media_assistant_streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - uploads:/app/uploads
      - logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_media_assistant_celery_worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
      - uploads:/app/uploads
      - logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Beat (Scheduler)
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_media_assistant_celery_beat
    command: celery -A celery_app beat --loglevel=info --schedule=/app/celerybeat-schedule
    volumes:
      - .:/app
      - uploads:/app/uploads
      - logs:/app/logs
      - beat_data:/app/celerybeat-schedule
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Redis (Message Broker)
  redis:
    image: redis:7-alpine
    container_name: social_media_assistant_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

# Named volumes for data persistence
volumes:
  uploads:
  logs:
  redis_data:
  beat_data:
